name: molit-daily

on:
  schedule:
    - cron: "5 0 * * *"   # 09:05 KST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Decode SA json
        run: |
          echo "${{ secrets.GDRIVE_SA_JSON }}" > sa.json

      - name: Run job
        timeout-minutes: 20
        env:
          TZ: Asia/Seoul
          CI: "1"
          SA_PATH: ${{ github.workspace }}/sa.json
          SHEET_ID: ${{ secrets.SHEET_ID }}             # (선택) 시트 연동 시 사용
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }} # (선택) GDrive 업로드 시 사용
          DRIVE_RETENTION_DAYS: "3"                      # (선택)
        run: python rt_allinone.py
