name: 몰리트

on:
  schedule:
    - cron: "5 0 * * *"   # 매일 09:05 KST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CI: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Chromium & Chromedriver
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write service account json
        run: |
          set -euxo pipefail
          # GDRIVE_SA_JSON은 "원본 JSON"을 줄바꿈 포함 그대로 붙여넣어야 합니다.
          printf "%s" "${{ secrets.GDRIVE_SA_JSON }}" > sa.json || true

      - name: Run job
        timeout-minutes: 20
        env:
          TZ: Asia/Seoul
          SA_PATH: ${{ github.workspace }}/sa.json
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          DRIVE_RETENTION_DAYS: "3"
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          set -euxo pipefail
          python rt_allinone.py | tee runlog.txt

      - name: Upload outputs as artifact (keep 3 days)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs-${{ github.run_id }}
          path: |
            output/*.xlsx
            runlog.txt
          retention-days: 3
          if-no-files-found: warn
