name: molit-daily

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"    # 08:00 KST
    - cron: "30 23 * * *"   # 08:30 KST (백업)

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      CI: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Chromium & Chromedriver
        run: |
          set -euxo pipefail
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps (with log)
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt --default-timeout=120 -v 2>&1 | tee pip-install.log

      - name: Write service account json (optional)
        run: |
          set -euxo pipefail
          printf "%s" "${{ secrets.GDRIVE_SA_JSON }}" > sa.json || true

      - name: Run job
        timeout-minutes: 45
        env:
          TZ: Asia/Seoul
          SA_PATH: ${{ github.workspace }}/sa.json
          DOWNLOAD_TIMEOUT: "30"
          CLICK_RETRY_MAX: "15"
          CLICK_RETRY_WAIT: "1"
          ARTIFACTS_ONLY: "1"
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          DRIVE_RETENTION_DAYS: "3"
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          set -euxo pipefail
          python rt_allinone.py 2>&1 | tee runlog.txt

      - name: Upload outputs as artifact (keep 3 days)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: outputs-${{ github.run_id }}
          retention-days: 3
          path: |
            output/*.xlsx
            runlog.txt
            pip-install.log
