name: molit-daily

on:
  schedule:
    # 매일 09:05 KST == 00:05 UTC
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 90

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 크롬/드라이버 설치 (snap이라 시간이 좀 걸립니다)
      - name: Install Chromium & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 서비스계정 JSON을 sa.json로 저장 (멀티라인을 안전하게 처리)
      - name: Write service account json
        shell: bash
        run: |
          cat > sa.json <<'JSON'
          ${{ secrets.GDRIVE_SA_JSON }}
          JSON

      - name: Run job (download + preprocess + upload + write to Sheets)
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          SA_PATH:  ${{ github.workspace }}/sa.json
          CHROME_BIN: /usr/bin/chromium-browser
          CHROMEDRIVER_BIN: /usr/bin/chromedriver
          PYTHONUNBUFFERED: "1"   # 파이썬 버퍼링 끔
          TZ: Asia/Seoul
        run: |
          set -e
          echo "== versions =="
          python -V
          /usr/bin/chromium-browser --version || true
          /usr/bin/chromedriver --version || true
          echo "== start script =="
          python -u rt_allinone.py   # <-- 꼭 -u
