name: molit-daily

on:
  schedule:
    # 매일 09:05 KST == 00:05 UTC
    - cron: "5 0 * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 크롬 & 크롬드라이버 설치 (Ubuntu, headless 용)
      - name: Install Chromium & Chromedriver
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run job (download + preprocess + upload + write to Sheets)
        env:
          SHEET_ID: ${{ secrets.SHEET_ID }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          SA_PATH:  ${{ github.workspace }}/sa.json
          CHROME_BIN: /usr/bin/chromium-browser
          CHROMEDRIVER_BIN: /usr/bin/chromedriver
          PYTHONUNBUFFERED: "1"
          TZ: Asia/Seoul
        run: |
          python -V
          /usr/bin/chromium-browser --version || true
          /usr/bin/chromedriver --version || true
          python -u rt_allinone.py   # <= 여기 -u


      # 서비스계정 키 JSON을 sa.json 파일로 저장
      - name: Write service account json
        run: |
          printf "%s" "${{ secrets.GDRIVE_SA_JSON }}" > sa.json

      # (선택) 크롬 스모크 테스트 - 드라이버/헤드리스 정상동작 여부 빠르게 확인
      - name: Smoke test Chrome
        env:
          CHROME_BIN: /usr/bin/chromium-browser
          CHROMEDRIVER_BIN: /usr/bin/chromedriver
          PYTHONUNBUFFERED: "1"
        run: |
          python - <<'PY'
          import os
          from selenium import webdriver
          from selenium.webdriver.chrome.options import Options
          from selenium.webdriver.chrome.service import Service
          o=Options()
          o.add_argument("--headless=new")
          o.add_argument("--no-sandbox")
          o.add_argument("--disable-dev-shm-usage")
          o.binary_location=os.environ.get("CHROME_BIN")
          s=Service(os.environ.get("CHROMEDRIVER_BIN"))
          d=webdriver.Chrome(service=s, options=o)
          print("SMOKE: chrome ok")
          d.quit()
          PY

      - name: Run job (download + preprocess + upload + write to Sheets)
        env:
          # 시크릿에서 주입되는 값들
          SHEET_ID: ${{ secrets.SHEET_ID }}
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}

          # 워크스페이스 내 실제 파일 경로
          SA_PATH:  ${{ github.workspace }}/sa.json

          # 크롬 경로 (위에서 export 한 값)
          CHROME_BIN: /usr/bin/chromium-browser
          CHROMEDRIVER_BIN: /usr/bin/chromedriver

          # 로그 버퍼링 끄기 + KST 타임존
          PYTHONUNBUFFERED: "1"
          TZ: Asia/Seoul
        run: |
          python -V
          /usr/bin/chromium-browser --version || true
          /usr/bin/chromedriver --version || true
          python -u rt_allinone.py
