name: molit-daily

on:
  schedule:
    - cron: "5 0 * * *"   # KST 09:05
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Chromium
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-browser chromium-chromedriver
          echo "CHROME_BIN=/usr/bin/chromium-browser" >> $GITHUB_ENV
          echo "CHROMEDRIVER_BIN=/usr/bin/chromedriver" >> $GITHUB_ENV

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 서비스계정 JSON을 파일로 저장
      - name: Write SA JSON
        run: |
          printf '%s' "${GDRIVE_SA_JSON}" > sa.json
        env:
          GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}

      - name: Run script
        env:
          TZ: Asia/Seoul
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          DRIVE_RETENTION_DAYS: ${{ secrets.DRIVE_RETENTION_DAYS }}
          SA_PATH: ${{ github.workspace }}/sa.json
        run: |
          python rt_allinone.py
