name: molit-daily

on:
  workflow_dispatch:
  schedule:
    - cron: "5 0 * * *"   # 매일 09:05 KST

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    env:
      CI: "1"
      PYTHONUNBUFFERED: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Print runner info
        run: |
          set -euxo pipefail
          python --version
          pip --version
          uname -a

      # Chrome을 스냅 대신 빠르게 설치 (속도/안정성 ↑)
      - name: Setup Chrome
        id: chrome
        uses: browser-actions/setup-chrome@v1

      - name: Export CHROME_BIN
        run: |
          set -euxo pipefail
          echo "CHROME_BIN=${{ steps.chrome.outputs.chrome-path }}" >> $GITHUB_ENV
          which chromedriver || true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -c "import selenium, sys; print('Selenium:', selenium.__version__); sys.stdout.flush()"

      # 필수 시크릿 존재 확인 (여기서 바로 실패 원인 보이게)
      - name: Check required secrets
        run: |
          set -euxo pipefail
          test -n "${{ secrets.GDRIVE_SA_JSON }}" || { echo "❌ GDRIVE_SA_JSON is missing"; exit 1; }
          test -n "${{ secrets.DRIVE_FOLDER_ID }}" || { echo "❌ DRIVE_FOLDER_ID is missing"; exit 1; }
          test -n "${{ secrets.SHEET_ID }}" || { echo "❌ SHEET_ID is missing"; exit 1; }
          echo "✅ All required secrets exist."

      - name: Write service account json
        env:
          GDRIVE_SA_JSON: ${{ secrets.GDRIVE_SA_JSON }}
        run: |
          set -euxo pipefail
          printf "%s" "$GDRIVE_SA_JSON" > sa.json
          python - <<'PY'
import json,sys
try:
    with open("sa.json","r",encoding="utf-8") as f:
        j=json.load(f)
    print("SA OK:", j.get("client_email","(no client_email)")); sys.stdout.flush()
except Exception as e:
    print("SA JSON invalid:", e); sys.stdout.flush(); sys.exit(1)
PY

      - name: Run job (download + preprocess + upload + write to Sheets)
        timeout-minutes: 20
        env:
          TZ: Asia/Seoul
          SA_PATH: ${{ github.workspace }}/sa.json
          DRIVE_FOLDER_ID: ${{ secrets.DRIVE_FOLDER_ID }}
          DRIVE_RETENTION_DAYS: "3"
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          set -euxo pipefail
          python rt_allinone.py 2>&1 | tee runlog.txt

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: run-logs
          path: |
            runlog.txt
            sa.json
          if-no-files-found: warn
